name: HumeAI-SDK-CI

on:
  push:
    branches:
      - main
    paths:
      - backend/src/humeai_sdk/**
      - backend/tests/packages/humeai_sdk/**
      - .github/workflows/common-ci-python.yaml
      - .github/workflows/humeai-sdk-ci.yaml
  pull_request:
    branches:
      - main
      # Note: Path filtering is handled by the paths-filter action (see https://github.com/HumeAI/hume/wiki/GitHub-Actions)

jobs:
  build-humeai-sdk:
    uses: ./.github/workflows/common-ci-python.yaml
    with:
      package_name: humeai-sdk
      package_source_path: backend/src/humeai_sdk
      package_tests_path: backend/tests/packages/humeai_sdk
      artifact_registry_project: hume-data
      artifact_registry_region: us-east4
      artifact_registry_repo: humepy
      filter_paths: |
        src:
          - backend/src/humeai_sdk/**
          - backend/tests/packages/humeai_sdk/**
          - .github/workflows/common-ci-python.yaml
          - .github/workflows/humeai-sdk-ci.yaml
    secrets:
      aws_access_key_id: ${{ secrets.AWS_TRANSCRIPTION_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_TRANSCRIPTION_SECRET_ACCESS_KEY }}
      aws_default_region: ${{ secrets.AWS_TRANSCRIPTION_DEFAULT_REGION }}
      gcp_account_password: ${{ secrets.GCP_ACCOUNT_PASSWORD }}
      gcp_account_credentials: ${{ secrets.GCP_CREDENTIALS }}
      hume_dev_api_key: ${{ secrets.HUME_DEV_API_KEY }}
