# This file was auto-generated by Fern from our API Definition.

import os

import pytest
from hume.client import AsyncHumeClient, HumeClient


@pytest.fixture
def client() -> HumeClient:
    return HumeClient(
        api_key=os.getenv("ENV_API_KEY", "api_key"),
        base_url=os.getenv("TESTS_BASE_URL", "base_url"),
    )


@pytest.fixture
def async_client() -> AsyncHumeClient:
    return AsyncHumeClient(
        api_key=os.getenv("ENV_API_KEY", "api_key"),
        base_url=os.getenv("TESTS_BASE_URL", "base_url"),
    )
