# This file was auto-generated by Fern from our API Definition.

import typing

from .octave_output_timestamp import OctaveOutputTimestamp
from .snippet_audio_chunk import SnippetAudioChunk

SynthesizeJsonStreamingResponse = typing.Union[OctaveOutputTimestamp, SnippetAudioChunk]
