# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReturnPrompt(UniversalBaseModel):
    """
    A specific prompt version returned from the server
    """

    created_on: int = pydantic.Field()
    """
    The timestamp when the first version of this prompt was created.
    """

    id: str = pydantic.Field()
    """
    Identifier for a Prompt. Formatted as a UUID.
    """

    modified_on: int = pydantic.Field()
    """
    The timestamp when this version of the prompt was created.
    """

    name: str = pydantic.Field()
    """
    Name applied to all versions of a particular Prompt.
    """

    text: str = pydantic.Field()
    """
    Text used for this version of the Prompt.
    """

    version: int = pydantic.Field()
    """
    Version number for a Prompt. Version numbers should be integers. The combination of configId and version number is unique.
    """

    version_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description that is appended to a specific version of a Prompt.
    """

    version_type: str = pydantic.Field()
    """
    Indicates whether this prompt is using a fixed version number or auto-updating to the latest version. Values from the VersionType enum.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
