# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .returned_webhook_spec_events_item import ReturnedWebhookSpecEventsItem
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ReturnedWebhookSpec(UniversalBaseModel):
    """
    Collection of webhook URL endpoints to be returned from the server
    """

    url: str = pydantic.Field()
    """
    Webhook URL to send the event updates to
    """

    events: typing.List[ReturnedWebhookSpecEventsItem] = pydantic.Field()
    """
    Events this URL is subscribed to
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
