# This file was auto-generated by Fern from our API Definition.

from ....core.pydantic_utilities import UniversalBaseModel
import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class BoundingBox(UniversalBaseModel):
    """
    A bounding box around a face.
    """

    x: float = pydantic.Field()
    """
    x-coordinate of bounding box top left corner.
    """

    y: float = pydantic.Field()
    """
    y-coordinate of bounding box top left corner.
    """

    w: float = pydantic.Field()
    """
    Bounding box width.
    """

    h: float = pydantic.Field()
    """
    Bounding box height.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
