# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class StateEmbeddingGeneration_Queued(UniversalBaseModel):
    status: typing.Literal["QUEUED"] = "QUEUED"
    created_timestamp_ms: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class StateEmbeddingGeneration_InProgress(UniversalBaseModel):
    status: typing.Literal["IN_PROGRESS"] = "IN_PROGRESS"
    created_timestamp_ms: int
    started_timestamp_ms: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class StateEmbeddingGeneration_Completed(UniversalBaseModel):
    status: typing.Literal["COMPLETED"] = "COMPLETED"
    created_timestamp_ms: int
    started_timestamp_ms: int
    ended_timestamp_ms: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class StateEmbeddingGeneration_Failed(UniversalBaseModel):
    status: typing.Literal["FAILED"] = "FAILED"
    created_timestamp_ms: int
    started_timestamp_ms: int
    ended_timestamp_ms: int
    message: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


StateEmbeddingGeneration = typing_extensions.Annotated[
    typing.Union[
        StateEmbeddingGeneration_Queued,
        StateEmbeddingGeneration_InProgress,
        StateEmbeddingGeneration_Completed,
        StateEmbeddingGeneration_Failed,
    ],
    pydantic.Field(discriminator="status"),
]
